# fly.toml app configuration file generated for snrt-search on 2025-05-16T01:23:48+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'snrt-search'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  # Environment variables will be set via fly secrets

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    interval = '10s'
    timeout = '5s'
    grace_period = '10s'
    method = 'get'
    path = '/health'
    protocol = 'http'
    tls_skip_verify = false

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
